# Generated by Django 3.0.6 on 2020-05-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='szkolenie',
            name='Provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
