# Generated by Django 3.0.6 on 2020-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_szkolenie_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='szkolenie',
            name='max_participants',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
