# Generated by Django 3.0.6 on 2020-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_szkolenie_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szkolenie',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
