# Generated by Django 3.0.6 on 2020-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20200602_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szkolenie',
            name='Provider',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='szkolenie',
            name='max_participants',
            field=models.IntegerField(max_length=10),
        ),
    ]
