# Generated by Django 3.0.6 on 2020-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20200917_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='szkolenie',
            name='max_participants',
            field=models.IntegerField(),
        ),
    ]
