# Generated by Django 3.0.6 on 2020-09-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20200918_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='email',
            new_name='email_user',
        ),
    ]
