# Generated by Django 3.0.6 on 2020-09-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20200919_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='name',
            new_name='name_user',
        ),
    ]
