# Generated by Django 3.0.6 on 2020-09-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20200921_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='full_name',
            new_name='full_name_company',
        ),
    ]
