# Generated by Django 3.0.6 on 2020-10-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20201004_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='szkolenie',
            name='archiwum',
            field=models.BooleanField(default=False),
        ),
    ]
