# Generated by Django 3.0.6 on 2020-10-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20201018_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='sent',
        ),
        migrations.CreateModel(
            name='send_email_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_email', models.BooleanField(default=True)),
                ('name_message_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Message_email')),
                ('neme_user_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Panel')),
            ],
        ),
    ]
