# Generated by Django 3.0.6 on 2020-05-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='register_try',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
