# Generated by Django 3.0.6 on 2020-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0002_myusers_register_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
