# Generated by Django 3.0.6 on 2020-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0003_myusers_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
