# Generated by Django 3.0.6 on 2020-06-07 13:22

import MyUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0004_myusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=MyUser.models.path_file_name, validators=[MyUser.models.validate_image], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
